[bionic]
linux-generic = {installPackages = "linux-generic linux-headers-generic linux-image-generic"}
"linux-generic-hwe-18.04" = {installPackages = "linux-generic-hwe-18.04 linux-headers-generic-hwe-18.04 linux-image-generic-hwe-18.04"}
"linux-generic-hwe-18.04-edge" = {installPackages = "linux-generic-hwe-18.04-edge linux-headers-generic-hwe-18.04-edge linux-image-generic-hwe-18.04-edge"}


[focal]
linux-generic = {installPackages = "linux-generic linux-headers-generic linux-image-generic"}
"linux-generic-hwe-20.04" = {installPackages = "linux-generic-hwe-20.04 linux-headers-generic-hwe-20.04 linux-image-generic-hwe-20.04"}
"linux-generic-hwe-20.04-edge" = {installPackages = "linux-generic-hwe-20.04-edge linux-headers-generic-hwe-20.04-edge linux-image-generic-hwe-20.04-edge"}
"linux-oem-20.04" = {installPackages = "linux-oem-20.04 linux-oem-20.04b linux-headers-oem-20.04b linux-image-oem-20.04b"}
"linux-oem-20.04-edge" = {installPackages = "linux-oem-20.04-edge linux-oem-20.04b linux-headers-oem-20.04b linux-image-oem-20.04b"}
"linux-tuxedo-20.04" = {installPackages = "linux-tuxedo-20.04 linux-headers-tuxedo-20.04 linux-image-tuxedo-20.04"}
"linux-tuxedo-20.04-edge" = {installPackages = "linux-tuxedo-20.04-edge linux-headers-tuxedo-20.04-edge linux-image-tuxedo-20.04-edge"}
"linux-tuxedo-20.04-next" = {installPackages = "linux-tuxedo-20.04-next linux-headers-tuxedo-20.04-next linux-image-tuxedo-20.04-next"}


[jammy]
linux-aws = {installPackages = "linux-aws linux-headers-aws linux-image-aws"}
linux-generic = {installPackages = "linux-generic linux-headers-generic linux-image-generic"}
"linux-tuxedo-22.04" = {installPackages = "linux-tuxedo-22.04 linux-headers-tuxedo-22.04 linux-image-tuxedo-22.04"}
"linux-tuxedo-22.04-edge" = {installPackages = "linux-tuxedo-22.04-edge linux-headers-tuxedo-22.04-edge linux-image-tuxedo-22.04-edge"}
"linux-tuxedo-22.04-next" = {installPackages = "linux-tuxedo-22.04-next linux-headers-tuxedo-22.04-next linux-image-tuxedo-22.04-next"}
