###############################################################################
# list of supported OS versions
# with repective repo entries
#
# NAME
#     versions
#         VERSION_ID
#             name = VERSION_CODENAME
# 

"TUXEDO OS" = ["20.04", "22.04"]
"TUXEDO_OS Plasma" = ["20.04", "22.04"]
"KDE neon" = ["20.04", "22.04"]
"Ubuntu" = ["18.04", "20.04", "22.04"]


"Linux Mint" = ["21.1", "21.2", "21.3"]
"elementary OS" = ["6.1", "7.1"]
