["KDE neon 20.04"]
name = "focal"
["KDE neon 20.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "a8dc9203f21d5a80f5b3abe7545e8736"
["KDE neon 20.04".graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
hashvalue = "b831d0c0e5b086ab0bc659025f76ec71"
["KDE neon 20.04".oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"
hashvalue = "b4774d5ba5988bc1f56c19fee81105c3"

["KDE neon 22.04"]
name = "jammy"
["KDE neon 22.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"


["Linux Mint 21.1"]
name = "jammy"
["Linux Mint 21.1".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"

["Linux Mint 21.2"]
name = "jammy"
["Linux Mint 21.2".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"


["TUXEDO OS 20.04"]
name = "focal"
["TUXEDO OS 20.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "a8dc9203f21d5a80f5b3abe7545e8736"
["TUXEDO OS 20.04".graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
hashvalue = "b831d0c0e5b086ab0bc659025f76ec71"
["TUXEDO OS 20.04".oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"
hashvalue = "b4774d5ba5988bc1f56c19fee81105c3"

["TUXEDO OS 22.04"]
name = "jammy"
["TUXEDO OS 22.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"


["TUXEDO_OS Plasma 20.04"]
name = "focal"
["TUXEDO_OS Plasma 20.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "a8dc9203f21d5a80f5b3abe7545e8736"
["TUXEDO_OS Plasma 20.04".graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
hashvalue = "b831d0c0e5b086ab0bc659025f76ec71"
["TUXEDO_OS Plasma 20.04".oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"
hashvalue = "b4774d5ba5988bc1f56c19fee81105c3"

["TUXEDO_OS Plasma 22.04"]
name = "jammy"
["TUXEDO_OS Plasma 22.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"


["Ubuntu 18.04"]
name = "bionic"
["Ubuntu 18.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu bionic main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "76dfb9a4fd331c07e5f429adc9b07342"
["Ubuntu 18.04".graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu bionic main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
hashvalue = "bd9eb5abf560a9b9781df50990f006a1"
["Ubuntu 18.04".oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu bionic main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"
hashvalue = "45fe8814b157049c4ca98dc7f2fec204"

["Ubuntu 20.04"]
name = "focal"
["Ubuntu 20.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "a8dc9203f21d5a80f5b3abe7545e8736"
["Ubuntu 20.04".graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
hashvalue = "b831d0c0e5b086ab0bc659025f76ec71"
["Ubuntu 20.04".oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"
hashvalue = "b4774d5ba5988bc1f56c19fee81105c3"

["Ubuntu 22.04"]
name = "jammy"
["Ubuntu 22.04".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"


["elementary OS 6.1"]
name = "6.1 jolnir"
["elementary OS 6.1".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "a8dc9203f21d5a80f5b3abe7545e8736"
["elementary OS 6.1".graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
hashvalue = "b831d0c0e5b086ab0bc659025f76ec71"
["elementary OS 6.1".oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"
hashvalue = "b4774d5ba5988bc1f56c19fee81105c3"

["elementary OS 7.1"]
name = "7.1 horus"
["elementary OS 7.1".deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
hashvalue = "abca6201e010d01e36e3ab8cba94d4b1"
