[bionic]
[bionic.mirrors]
content = ["deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu bionic main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu bionic-security main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse"]
filename = "/etc/apt/sources.list.d/tuxedo-ubuntu-mirrors.list"

[focal]
[focal.mirrors]
content = ["deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu focal main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu focal-security main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse"]
filename = "/etc/apt/sources.list.d/tuxedo-ubuntu-mirrors.list"

[jammy]
[jammy.mirrors]
content = ["deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse"]
filename = "/etc/apt/sources.list.d/tuxedo-ubuntu-mirrors.list"


["Linux Mint 21.1"]
name = "vanessa"
["Linux Mint 21.1".mirrors]
content = ["deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse",
            "deb http://packages.linuxmint.com vanessa main upstream import backport"]
filename = "/etc/apt/sources.list.d/official-package-repositories.list"

["Linux Mint 21.2"]
name = "victoria"
["Linux Mint 21.2".mirrors]
content = ["deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse",
            "deb http://packages.linuxmint.com victoria main upstream import backport"]
filename = "/etc/apt/sources.list.d/official-package-repositories.list"

["Linux Mint 21.3"]
name = "virginia"
["Linux Mint 21.3".mirrors]
content = ["deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse", "deb https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse",
            "deb http://packages.linuxmint.com virginia main upstream import backport"]
filename = "/etc/apt/sources.list.d/official-package-repositories.list"
