[bionic]
[bionic.deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu bionic main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
[bionic.graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu bionic main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
[bionic.oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu bionic main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"


[focal]
[focal.deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
[focal.graphics]
content = ["deb https://graphics.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/graphics-tuxedo.list"
[focal.oibaf]
content = ["deb https://oibaf.tuxedocomputers.com/ubuntu focal main"]
filename = "/etc/apt/sources.list.d/oibaf-tuxedo.list"


[jammy]
[jammy.deb]
content = ["deb https://deb.tuxedocomputers.com/ubuntu jammy main"]
filename = "/etc/apt/sources.list.d/tuxedo-computers.list"
